### PR TITLE
Update youtube.txt

### PR DESCRIPTION
**Pull request by MEP239**
I keep misclicking yt shorts. Im not feeling very happy now.

### CODE REVIEW

**Comment by MEP239** [comment]
he even deleted the comments that were telling him "Maybe dont spam your server on comment sections"

**Comment by MEP239** [comment]
you know why i didnt go well you know

**Comment by smordarski** [comment]
Hello @MEP239, I will be reviewing this pull request. Our company had to reinstall the server operating system. We accidently deleted some files but everything is okay right now. Git is all setup so we can contribute again to this filter list.

**Comment by smordarski** [comment]
I just merged this in commit https://github.com/Mordarski-Networks/Mordarski-Networks-assets/commit/5a5563b018e4160a03f0b78248e24d56ac2547a3.

**Comment by MEP239** [comment]
> Hello @MEP239, I will be reviewing this pull request. Our company had to reinstall the server operating system. We accidently deleted some files but everything is okay right now. Git is all setup so we can contribute again to this filter list.

What+Is+Formal+Language

**Comment by MEP239** [comment]
jk

**Pull request merged**
